[features]
seeds = false
skip-lint = false
[programs.devnet]
blogger_dapp = "D2jGWop9j2ztWdVgkoa5cPM9t7FETdG7HoTEbERFnkGw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anoy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
